### PR TITLE
Posef extensions update & controller update

### PR DESCRIPTION
**Pull request by StephenHodgson**
## Overview

Updated the `Posef` extensions to be more concise and adjusted the controller's frame of reference.

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
Need to test this, as when I applied the same, it did not work as the HeadPose was offset out of alignment with the controllers.

**Comment by StephenHodgson** [comment]
Yeah this wasn't trying to address the offset yet. Maybe in another pass

**Comment by SimonDarksideJ** [comment]
Solved the Controller height issue by replicating what Unity is doing with WMR and OpenVR (Steam) by adjusting for controller height in the driver using the eyeheight

**Comment by StephenHodgson** [comment]
Do you also want to bump the version number and make a release?

**Pull request merged**
