### PR TITLE
Reorganised Oculus assets to support Issue Core #664

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Oculus Controller Input Action mappings were depending on the OpenVR controller input action mappings, however when these were moved to the oculus package, the mappings were not moved too.

## Changes

- Added Controller Input Action mappings for Oculus Touch controllers
- Reorganized assets to match SDK

- Fixes: https://github.com/XRTK/XRTK-Core/issues/664

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Were these files removed from another package and added to this one?

**Comment by SimonDarksideJ** [comment]
> Were these files removed from another package and added to this one?

No, because if I removed them from the SDK, then OpenVR would cease to work

**Comment by StephenHodgson** [comment]
When we transition to the native streamVR implementation, we should probably do the same and then completely remove.

**Comment by SimonDarksideJ** [comment]
Agreed, in the move to SteamVR, those assets will also transition/or be replaced.

**Review by FejZa — APPROVED** [review]
Cool. I agree once the OpenVR/SteamVR package is ready the ones in SDK can be fully removed.

**Pull request merged**
